### ISSUE TITLE
Skipped block ranges without retry

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#205]
From the log of snapshot creation:
```
getting blocks: trying #1 - from:18938069 to:18940069
getting blocks: trying #1 - from:18940070 to:18942070
Error: Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
    at Object.InvalidResponse (/home/sentinel/superfluid-sentinel/node_modules/web3-providers-http/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (/home/sentinel/superfluid-sentinel/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
getting blocks: trying #1 - from:18942071 to:18944071
Error: Returned error: Internal JSON-RPC error.
    at Object.ErrorResponse (/home/sentinel/superfluid-sentinel/node_modules/web3-core-requestmanager/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/sentinel/superfluid-sentinel/node_modules/web3-core-requestmanager/lib/index.js:302:36
    at XMLHttpRequest.request.onreadystatechange (/home/sentinel/superfluid-sentinel/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/sentinel/superfluid-sentinel/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  data: null
}
getting blocks: trying #1 - from:18944072 to:18946072
```

What's surprising here: one would expect instaces of _getting blocks: trying #2_ (see https://github.com/superfluid-finance/superfluid-sentinel/blob/master/src/boot/loadEvents.js#L36), but none occur.
The snapshot creation script has [MAX_RETRIES: 10](https://github.com/superfluid-finance/superfluid-sentinel/blob/master/scripts/buildSnapshot.js#L33) set. If reaching the retry limit, it should exit.

In case events are missed, this may be related to https://github.com/superfluid-finance/superfluid-sentinel/issues/187

**Comment by ngmachado** [comment]
Fixed with https://github.com/superfluid-finance/superfluid-sentinel/pull/206
```
2023-04-18T14:00:09.949Z - info: getting blocks: trying #1 - from:18824006 to:18828006
2023-04-18T14:00:23.236Z - error: Returned error: Internal JSON-RPC error.
2023-04-18T14:00:25.237Z - info: getting blocks: trying #2 - from:18824006 to:18828006
2023-04-18T14:01:26.758Z - info: getting blocks: trying #1 - from:18828007 to:18832007
```
